In [19]:
import numpy as np
my_array = [10, 20, 30]
print(my_array)

my_new_array = [1, 2, 3, 4, 5, 6]
print(my_new_array)

bias_array = [0.1, 0.5, -0.2]
print(bias_array)
x = np.array(my_array)
y = np.array([0.5, 0.2, 0.3])
b = np.array(bias_array)

z=np.dot(x,y)+b
print(z)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid_z = sigmoid(z)
print(f"Original z: {z}")
print(f"Sigmoid of z: {sigmoid_z}")
input_layer_1 = np.array([5, 10, 15])
input_layer_2 = np.array([2, 4, 6])
weights_layer_1 = np.array([0.1, 0.2, 0.3])
weights_layer_2 = np.array([0.4, 0.1, 0.2])
output_1 = np.dot(input_layer_1, weights_layer_1)
output_2 = np.dot(input_layer_2, weights_layer_2)
final_output = output_1 + output_2

print(f"Input Layer 1: {input_layer_1}")
print(f"Weights Layer 1: {weights_layer_1}")
print(f"Output from Layer 1: {output_1}\n")

print(f"Input Layer 2: {input_layer_2}")
print(f"Weights Layer 2: {weights_layer_2}")
print(f"Output from Layer 2: {output_2}\n")

print(f"Final Output: {final_output}")

[10, 20, 30]
[1, 2, 3, 4, 5, 6]
[0.1, 0.5, -0.2]
[18.1 18.5 17.8]
Original z: [18.1 18.5 17.8]
Sigmoid of z: [0.99999999 0.99999999 0.99999998]
Input Layer 1: [ 5 10 15]
Weights Layer 1: [0.1 0.2 0.3]
Output from Layer 1: 7.0

Input Layer 2: [2 4 6]
Weights Layer 2: [0.4 0.1 0.2]
Output from Layer 2: 2.4000000000000004

Final Output: 9.4


# Task
Implement a simple feedforward neural network using NumPy, defining inputs, weights, and biases for a hidden layer and an output layer, calculating the hidden layer's output with an activation function, then calculating the final output layer's output, and finally, summarize the feedforward network implementation including the inputs, weights, biases, and the final output.

## Define Input, Weights, and Biases for Hidden Layer

### Subtask:
Initialize input data, weights, and biases for the first (hidden) layer of the neural network using NumPy arrays.


**Reasoning**:
The subtask requires defining input data, weights, and biases for the first hidden layer using NumPy arrays. I will create a code block to initialize these variables with example values.



In [20]:
input_data = np.array([1, 2, 3])
hidden_weights = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
hidden_biases = np.array([0.1, 0.2])

print(f"Input Data: {input_data}")
print(f"Hidden Weights:\n{hidden_weights}")
print(f"Hidden Biases: {hidden_biases}")
hidden_layer_input = np.dot(input_data, hidden_weights) + hidden_biases
hidden_layer_output = sigmoid(hidden_layer_input)

print(f"Weighted sum for Hidden Layer: {hidden_layer_input}")
print(f"Hidden Layer Output (after sigmoid activation): {hidden_layer_output}")
output_weights = np.array([[0.7], [0.8]])
output_biases = np.array([0.3])

print(f"Output Weights:\n{output_weights}")
print(f"Output Biases: {output_biases}")
output_layer_input = np.dot(hidden_layer_output, output_weights) + output_biases
final_output = sigmoid(output_layer_input)

print(f"Weighted sum for Output Layer: {output_layer_input}")
print(f"Final Output (after sigmoid activation): {final_output}")

Input Data: [1 2 3]
Hidden Weights:
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]
Hidden Biases: [0.1 0.2]
Weighted sum for Hidden Layer: [1.5 3.4]
Hidden Layer Output (after sigmoid activation): [0.81757448 0.96770454]
Output Weights:
[[0.7]
 [0.8]]
Output Biases: [0.3]
Weighted sum for Output Layer: [1.64646576]
Final Output (after sigmoid activation): [0.83841282]
